#!/bin/bash

# should enter script with repo root as current directory

#
# Download libraries into './lib_raw'. This directory will
# include many files that will not be needed.
#
function download_to_lib_raw {

  if [ -d ./lib_raw ]
  then
     echo "'./lib_raw' directory already exists. First remove it."
     exit 1;
  fi

  mkdir lib_raw
  cd lib_raw

  #
  #  Spinkit 1.2.2
  #    https://github.com/tobiasahlin/SpinKit
  #
  wget https://github.com/tobiasahlin/SpinKit/archive/1.2.2.zip
  unzip 1.2.2.zip
  rm 1.2.2.zip

  #
  #  jQuery modal v0.5.9
  #    https://github.com/kylefox/jquery-modal
  #
  wget https://github.com/kylefox/jquery-modal/archive/v0.5.9.zip
  unzip v0.5.9.zip
  rm v0.5.9.zip

  #
  #  Leaflet 1.0 beta
  #    https://github.com/Leaflet/Leaflet
  #
  wget https://github.com/Leaflet/Leaflet/archive/v1.0.0-beta.2.zip
  unzip v1.0.0-beta.2.zip
  rm v1.0.0-beta.2.zip

  #
  #  jQRangeSlider 5.7.1
  #    https://github.com/ghusse/jQRangeSlider
  #
  #  and create minified version: See
  #    https://github.com/ghusse/jQRangeSlider
  #
  wget https://github.com/ghusse/jQRangeSlider/archive/5.7.1.zip
  unzip 5.7.1.zip
  rm 5.7.1.zip

  cd jQRangeSlider-5.7.1
  sudo npm install
  sudo npm install -g grunt-cli
  grunt uglify

  cd ../..

}

#
# Copy files that will be needed by osm-timeslider into './lib'.
#
function make_lib_dir {
  echo "Copying files into 'lib'"
  pwd

  if [ -d ./lib ]
  then
     echo "'./lib' directory already exists. First remove it."
     exit 1;
  fi

  mkdir lib

  mkdir lib/jQRangeSlider-5.7.1
  cp lib_raw/jQRangeSlider-5.7.1/dest/jQAllRangeSliders-withRuler-min.js lib/jQRangeSlider-5.7.1
  cp lib_raw/jQRangeSlider-5.7.1/*.txt                                   lib/jQRangeSlider-5.7.1

  mkdir lib/Leaflet-1.0.0-beta.2
  cp lib_raw/Leaflet-1.0.0-beta.2/dist/leaflet.css   lib/Leaflet-1.0.0-beta.2
  cp lib_raw/Leaflet-1.0.0-beta.2/dist/leaflet.js    lib/Leaflet-1.0.0-beta.2
  cp lib_raw/Leaflet-1.0.0-beta.2/LICENSE            lib/Leaflet-1.0.0-beta.2

  mkdir lib/jquery-modal-0.5.9
  cp lib_raw/jquery-modal-0.5.9/jquery.modal.css     lib/jquery-modal-0.5.9
  cp lib_raw/jquery-modal-0.5.9/jquery.modal.min.js  lib/jquery-modal-0.5.9
  cp lib_raw/jquery-modal-0.5.9/LICENSE              lib/jquery-modal-0.5.9

  mkdir ./lib/SpinKit-1.2.2
  cp lib_raw/SpinKit-1.2.2/css/spinners/5-pulse.css  lib/SpinKit-1.2.2
  cp lib_raw/SpinKit-1.2.2/LICENSE                   lib/SpinKit-1.2.2

}

download_to_lib_raw

make_lib_dir

